version: '3'

services:
  db:
    image: 'postgres:15'
    container_name: 'java-postgres'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - DB_HOST=localhost

  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    ports:
      - '8082:8081'
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update